### ISSUE TITLE
window size. management 

### ISSUE THREAD

**Issue by Lupin** [EvanZhouDev/graphite#1]
the editor window's width can be unusable were the AI assitant uses two thirds of the width . there's no way to rescale the editor window
<img width="1470" alt="Capture d’écran 2024-08-08 à 09 19 00" src="https://github.com/user-attachments/assets/146a3d6f-6c31-4e17-98c2-e0e63e811e10">

**Comment by EvanZhouDev** [comment]
It appears this is due to the monospaced text (in a pre tag?) that it is generating. The editor window itself should be always around 1/3. But that being said, have you had any automatic text edit suggestions (in the blue boxes?) It should in theory use those instead of suggesting in monospaced text.

**Comment by EvanZhouDev** [comment]
@Lupin This issue has been fixed. Your chat should now go back to the normal sizing. I am so sorry for any inconvenience!
