### ISSUE TITLE
Cannot chat to Graphite (old)

### ISSUE THREAD

**Issue by chamoysans** [EvanZhouDev/graphite#2]
![image_2024-10-23_210247369](https://github.com/user-attachments/assets/b684c214-4533-4a2f-8619-5fc4c1e6e08c)

No matter what i do, I keep on encountering this damn thing over and over, Im sorry if i sound rude, I'm just annoyed, I already tried reducing the words, I already tried reloading, I tried any possible way i can think of, Please fix ASAP! It's alright if it takes a couple days, Just gotta resort to chatgpt for a while. Thanks though!

**Comment by EvanZhouDev** [comment]
Hey @chamoysans, Graphite works for me currently. I would recommend the following things:
1. Check if you can access Gemini normally (i.e. on the Gemini website)
2. Check if your API key is valid. Try generating a new one.
3. Ensure you aren't rate limited. Wait a minute and try again.
4. Start a new file and see if it works. Sometimes, Gemini may be blocking your request due to "safety" issues with your text, or prior chat questions.

If none of these things work, please let me know.

**Comment by EvanZhouDev** [comment]
@chamoysans any updates? I will close this issue for now. If it still doesn't work, feel free to reopen or just respond in this thread.

**Comment by chamoysans** [comment]
huh didnt know github had notifications

i did try a new doc, and it now worked (until now), it just... stopped working entirely? i did open a new file, then a new api key, i also did wait a minute but nothing, the new file is completely blank,

sorry for just ghosting you btw (had absolutely no idea, dont use github that often), good luck!

**Comment by chamoysans** [comment]
im just gonna create a new issue (i have absolutely no idea how to reopen an issue)
